version: "2"
services:
  frontend:
    build: ./Front-end
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    network_mode: "host"
  backend:
    env_file: "./Backend/.env"
    build: ./Backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    network_mode: "host"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
